# Workflow based on the following GitHub article:
# https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
name: Python

on: [push]

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with Pytest
        run: |
          python3 -m pytest -vv
      - name: Lint with Flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
